config/routes.rb
Rails.application.routes.draw do
  get '/', to: redirect('/maze/0/0/N')
  get '/maze/:x/:y/:direction', to: 'maze#maze', as: 'maze'
  resources :rooms
  resources :passages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
   validates :x, numericality: {only_integer: true}
   validates :y, numericality: {only_integer: true}
   validates :x, uniqueness: {scope: :y, message: ' and Y must be unique'}
   has_many :passages, foreign_key: :source_id

   def go_forward(direction)
      direction = Passage.normalize_direction(direction)
      p = self.passages.where(direction: direction).first
      return p.nil? ? nil : p.destination
   end

   def go_left(direction)
      direction = Passage.get_left_direction(direction)
      return self.go_forward(direction)
   end

   def go_right(direction)
      direction = Passage.get_right_direction(direction)
      return self.go_forward(direction)
   end

   def go_backward(direction)
      direction = Passage.get_backward_direction(direction)
      return self.go_forward(direction)
   end

   def get_destinations(direction)
      left_direction = Passage.get_left_direction(direction)
      right_direction = Passage.get_right_direction(direction)
      forward = self.go_forward(direction)
      backward = self.go_backward(direction)
      direction = Passage.short(direction)
      left_direction = Passage.short(left_direction)
      right_direction = Passage.short(right_direction)
      unless forward.nil?
         forward = ("%d/%d/%s" % [forward.x, forward.y, direction])
      end
      unless backward.nil?
         backward = ("%d/%d/%s" % [backward.x, backward.y, direction])
      end
      return {
         'left': ("%d/%d/%s" % [self.x, self.y, left_direction]),
         'forward': forward,
         'right': ("%d/%d/%s" % [self.x, self.y,  right_direction]),
         'backward': backward
      }
   end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
   def index
      @rooms = Room.all
   end

   def show
      @room = Room.find(params[:id])
   end

   def new
      @room = Room.new
   end

   def edit
      @room = Room.find(params[:id])
   end

   def create
      @room = Room.new(room_params)
      if @room.save
         redirect_to @room
      else
         render 'new'
      end
   end

   def update
      @room = Room.find(params[:id])
 
      if @room.update(room_params)
        redirect_to @room
      else
        render 'edit'
      end
   end

   def destroy
      @room = Room.find(params[:id])
      @room.destroy
      redirect_to rooms_path
   end

   private
      def room_params
         params.require(:room).permit(:x, :y)
      end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
 
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@room.errors.count, "error") %> prohibited
        this room from being saved:
      </h2>
      <ul>
        <% @room.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :x %><br>
    <%= f.text_field :x %>
  </p>
 
  <p>
    <%= f.label :y %><br>
    <%= f.text_field :y %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/rooms/edit.html.erb
<h1>Edit room</h1>
 
<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Rooms</h1>
 
<table>
  <tr>
    <th>x</th>
    <th>y</th>
  </tr>
 
  <% @rooms.each do |room| %>
    <tr>
      <td><%= room.x %></td>
      <td><%= room.y %></td>
      <td><%= link_to 'Show', room_path(room) %></td>
      <td><%= link_to 'Edit', edit_room_path(room) %></td>
      <td><%= link_to 'Destroy', room_path(room),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New room', new_room_path %>

app/views/rooms/index.json.erb
<%- @sep = "" %>
{
    "data": [<%- @rooms.each do |room| %><%= @sep %>{
        "id": <%= room.id %>,
        "x": <%= room.x %>,
        "y": <%= room.y %>
    }<% @sep = ", " %><% end %>]
}

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<h1>Room</h1>
<p>
  <strong>X,Y:</strong>
  <%= @room.x %>,
  <%= @room.y %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>