config/routes.rb
Rails.application.routes.draw do
  get '/', to: redirect('/maze/0/0/N')
  get '/maze/:x/:y/:direction', to: 'maze#maze', as: 'maze'
  resources :rooms
  resources :passages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/passage.rb
class Passage < ApplicationRecord
   belongs_to :source, class_name: 'Room'
   belongs_to :destination, class_name: 'Room'
   enum direction: [:north, :east, :south, :west]
   validates :direction, uniqueness: {scope: :source, message: ' room passage must be unique'}

   def get_direction()
      return self.direction.to_s.capitalize
   end

   def self.normalize_direction(direction)
      direction = direction.to_s.downcase
      character_direction = {
         :n => 'north',
         :north => 'north',
         :e => 'east',
         :east => 'east',
         :s => 'south',
         :south => 'south',
         :w => 'west',
         :west => 'west'
      }
      return character_direction[direction.to_sym].to_s
   end

   def self.short(direction)
      shorts = {
         :north => 'N',
         :east => 'E',
         :south => 'S',
         :west => 'W'
      }
      direction = Passage.normalize_direction(direction)
      return shorts[direction.to_sym]
   end

   def self.get_left_direction(direction)
      direction = self.normalize_direction(direction)
      idx = (Passage.directions[direction] - 1) % Passage.directions.length
      return Passage.directions.key(idx)
   end

   def self.get_right_direction(direction)
      direction = self.normalize_direction(direction)
      idx = (Passage.directions[direction] + 1) % Passage.directions.length
      return Passage.directions.key(idx)
   end

   def self.get_backward_direction(direction)
      direction = self.normalize_direction(direction)
      idx = (Passage.directions[direction] + 2) % Passage.directions.length
      return Passage.directions.key(idx)
   end
end

app/controllers/passages_controller.rb
class PassagesController < ApplicationController
   def index
      @passages = Passage.all
   end

   def show
      @passage = Passage.find(params[:id])
   end

   def new
      @passage = Passage.new
   end

   def edit
      @passage = Passage.find(params[:id])
   end

   def create
      @passage = Passage.new
      @passage.source = Room.find(params['passage']['source'])
      @passage.destination = Room.find(params['passage']['destination'])
      @passage.direction = params['passage']['direction'].to_i
      if @passage.save
         redirect_to @passage
      else
         render 'new'
      end
   end

   def update
      @passage = Passage.find(params[:id])
      @passage.source = Room.find(params['passage']['source'])
      @passage.destination = Room.find(params['passage']['destination'])
      @passage.direction = params['passage']['direction'].to_i
      if @passage.update()
        redirect_to @passage
      else
        render 'edit'
      end
   end

   def destroy
      @passage = Passage.find(params[:id])
      @passage.destroy
      redirect_to passages_path
   end
end

app/helpers/passages_helper.rb
module PassagesHelper
end

app/views/passages/_form.html.erb
<%= form_for(@passage) do |f| %>
 
  <% if @passage.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@passage.errors.count, "error") %> prohibited
        this passage from being saved:
      </h2>
      <ul>
        <% @passage.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :source %><br>
    <%= f.select :source, Room.all.collect { |p| [p.x.to_s + "," + p.y.to_s, p.id ] }, include_blank: true %>
  </p>
 
  <p>
    <%= f.label :destination %><br>
    <%= f.select :destination, Room.all.collect { |p| [p.x.to_s + "," + p.y.to_s, p.id ] }, include_blank: true %>
  </p>
 
  <p>
    <%= f.label :direction %><br>
    <%= f.select(:direction, options_for_select([['North',0],['East',1],['South',2],['West',3]], :selected => params[:direction])) %>
  </p>

  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/passages/edit.html.erb
<h1>Edit passage</h1>
 
<%= render 'form' %>

<%= link_to 'Back', passages_path %>

app/views/passages/index.html.erb
<h1>Passages</h1>
 
<table>
  <tr>
    <th>source</th>
    <th>destination</th>
    <th>direction</th>
  </tr>
 
  <% @passages.each do |passage| %>
    <tr>
      <td><%= passage.source.id %></td>
      <td><%= passage.destination.id %></td>
      <td><%= passage.direction %></td>
      <td><%= link_to 'Show', passage_path(passage) %></td>
      <td><%= link_to 'Edit', edit_passage_path(passage) %></td>
      <td><%= link_to 'Destroy', passage_path(passage),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New passage', new_passage_path %>

app/views/passages/index.json.erb
<%- @sep = "" %>
{
    "data": [<%- @passages.each do |passage| %><%= @sep %>{
        "id": <%= passage.id %>,
        "source_id": <%= passage.source.id %>,
        "destination_id": <%= passage.destination.id %>,
        "direction": "<%= passage.direction %>"
    }<% @sep = ", " %><% end %>]
}

app/views/passages/new.html.erb
<h1>New Passage</h1>

<%= render 'form' %>

<%= link_to 'Back', passages_path %>

app/views/passages/show.html.erb
<h1>Passage</h1>
<p>
  <strong>source:</strong>
  <%= @passage.source.x %>,
  <%= @passage.source.y %>
  <br>
  <strong>destination:</strong>
  <%= @passage.destination.x %>,
  <%= @passage.destination.y %>
  <br>
  <strong>direction:</strong> <%= @passage.direction %>
  <br>
</p>

<%= link_to 'Edit', edit_passage_path(@passage) %> |
<%= link_to 'Back', passages_path %>